POST http://localhost:5000/login/addUser
Content-Type: application/json

{
    "name": "Gabriele",
    "password": "Gabriele",
    "email": "gabriele@gmail.com"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "password": "User",
    "email": "user@gmail.com"
}

###
GET http://localhost:5000/autorization
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjgwMDE3NTk0MzQsIm5hbWUiOiJVc2VyIiwiaWF0IjoxNjI3OTk4MTU5fQ.1CmdWmOzX5sb6-X4dQ4kJ9_zwcquOXgI6nLjkgNKhtQ

###
POST http://localhost:5000/addTodo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjgwMDE3NTk0MzQsIm5hbWUiOiJVc2VyIiwiaWF0IjoxNjI3OTk4MTU5fQ.1CmdWmOzX5sb6-X4dQ4kJ9_zwcquOXgI6nLjkgNKhtQ

{
    "title": "prova",
    "body": "Questa è una prova",
    "expDate": "2021-08-03"
}
